version: "3.7"
services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fin_api
